// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_PF2gu_Qa8bvBbb-6X7ejv504HewAKw',
    appId: '1:218263612003:web:f9f96dd4420a335b4b2656',
    messagingSenderId: '218263612003',
    projectId: 'pinepinepine',
    authDomain: 'pinepinepine.firebaseapp.com',
    storageBucket: 'pinepinepine.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktzqfX4EroL-JtkqB5RdD6NR_BFxG7HQ',
    appId: '1:218263612003:android:2932fa3c273543264b2656',
    messagingSenderId: '218263612003',
    projectId: 'pinepinepine',
    storageBucket: 'pinepinepine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOadO8EWx7KRwTQqG0ujtEBO2giMS-0x0',
    appId: '1:218263612003:ios:890f27367ffa180d4b2656',
    messagingSenderId: '218263612003',
    projectId: 'pinepinepine',
    storageBucket: 'pinepinepine.appspot.com',
    iosClientId: '218263612003-gvn7biaio5ugctsjetcidtt06l2o022e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonproj',
  );
}
